title = "CBTV"
baseURL = "/"
# theme = "" 
resourceDir = "../resources"
disableModules = true
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
sectionPagesMenu = "main" 
enableRobotsTXT = true

[services.googleAnalytics]
id = ''

[pagination]
pagerSize = 5

[languages]
[languages.en]
disabled = false
contentDir = "content"
languageCode = 'en-GB'
weight = 1
[languages.en.params]
language = "English"

[languages.nl]
disabled = true
contentDir = "content/nl"
languageCode = 'nl'
weight = 2
[languages.nl.params]
language = "Dutch"

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
text_color = ""
author = ""
favicon = "favicon.ico"
site_logo = ""
description = "Where creativity meets opportunity"
recent_posts_number = 5
featured_image= 'images/home.png'
top_of_page= "images/up-arrow.png"

[params.social.facebook]
username = "ourmaninindia"
# profilelink = "https://www.facebook.com/ourmaninindia"

[params.social.linkedin]
username = "ourmaninindia"

[params.social.bluesky]
username = "ourmaninindia.dev"

[build]
useModules = false

[[menu.main]]
  name = "What is CBTV"
  url = "what-is-CBTV"
  weight = 1
  params = { id = "what-is-CBTV" }

[[menu.main]]
  name = "Design your future"
  url = "design-your-future"
  weight = 2
  params = { id = "design-your-future" }

[[menu.main]]
  name = "Building your own business"
  url = "building-your-own-business"
  weight = 3
  params = { id = "building-your-own-business" }

[[menu.main]]
  name = "The CBTV archive"
  url = "the-CBTV-archive"
  weight = 4
  params = { id = "the-CBTV-archive" }

[[menu.main]]
  name = "Student blogs"
  url = "student-blogs"
  weight = 5
  params = { id = "student-blogs" }

[[menu.main]]
  name = "Contact"
  url = "contact"
  weight = 6
  params = { id = "contact" }

[[menu.main]]
  name = "Send in your content"
  url = "send-in-your-content"
  weight = 7
  params = { id = "send-in-your-content" }
