[build]
command = "chmod +x node_modules/.bin/sass && npm install sass && hugo --gc --minify"
publish = "public"

[context.production.environment]
HUGO_VERSION = "0.138.0" # Specify your Hugo version
HUGO_ENV = "production"

