[build]
  command = "hugo --ignoreVendorPaths themes/* --minify --templateMetrics"
  publish = "public"

[context.production.environment]
HUGO_VERSION = "0.138.0" # Specify your Hugo version
HUGO_ENV = "production"

